- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
  - include_tasks: tasks/ssh.yml
  - include_tasks: tasks/git.yml
  - include_tasks: tasks/node.yml
 
